name: Build and Deploy DSM
on:
  push:
    branches: [config]
  pull_request:
    branches: [config]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          passphrase: ${{ secrets.DEV_PASSPHRASE }}
          rm: true
          source: "build/"
          target: "./"
